"""empty message

Revision ID: 1afdff6e021f
Revises: 5d4248bb842d
Create Date: 2019-12-02 17:38:13.741614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afdff6e021f'
down_revision = '5d4248bb842d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
